# Site settings
author: Paul Ashour
title: Juggling Lightning
header-img: img/home-bg.png
email: paul.ashour@gmail.com
copyright_name: Paul Ashour
description: > # this means to ignore newlines until "baseurl:"
  One person's attempt to comprehend what one person cannot comprehend
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  artrexdenthur

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
